### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by NoGitHubForYou** [stamparm/aux#10]
pihole reports some invalid domains...

```
  [i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 324616 exact domains and 0 ABP-style domains (ignored 4 non-domain entries)
      Sample of non-domain entries:
        - "noluyoruzawk"
        - "mpapwpodllalw"
        - "datacikerim"
        - "websplexml"
```

Thanks

**Comment by MikhailKasimov** [comment]
fix: https://github.com/stamparm/maltrail/commit/f9bf268d7c55119faf170c6b0682eaeb88f0c849
fix: https://github.com/stamparm/maltrail/commit/69d930b15825a3424976e8fa6e030eb5e11e85f5
fix: https://github.com/stamparm/maltrail/commit/63f8146edb6d6921c1d0046bcf220bf158b5f150

**Comment by stamparm** [comment]
@NoGitHubForYou thank you for the report. @MikhailKasimov fixed it. thus, changes should be visible here in next 24h (tops)

**Comment by NoGitHubForYou** [comment]
Noticed a few more invalid domains

```
anayinamiusom
birakyakamiorsupuogluusom312
```

**Comment by MikhailKasimov** [comment]
> Noticed a few more invalid domains
> 
> ```
> anayinamiusom
> birakyakamiorsupuogluusom312
> ```

Fixed in:

https://github.com/stamparm/maltrail/commit/dd8679bb9faa30403a294a4e50a95c70965ee018
https://github.com/stamparm/maltrail/commit/291f13378274fb4c4900c68ac27f9f2a162e2411

Thnx for letting know!
