### ISSUE TITLE
Enhancement: More aggressive blocking ruleset

### ISSUE THREAD

**Issue by NoGitHubForYou** [stamparm/aux#11]
Regarding file https://github.com/stamparm/aux/raw/master/maltrail-malware-domains.txt

I like to assume all subdomains of any entry in `/maltrail-malware-domains.txt` are potentially malicious as well. Would it be possible to add a second list `/maltrail-malware-adblock.txt` to be more aggressive in blocking?

Thanks

**Comment by e42sh** [comment]
I solved that by writing a tool that adds a `||...^` around each line. I used this to feed an Adguard Home app.

**Comment by NoGitHubForYou** [comment]
> I solved that by writing a tool that adds a `||...^` around each line. I used this to feed an Adguard Home app.

You're correct that I could do something like this too. I was just looking for something more "native" since a I manage several PiHole servers.

I actually wish PiHole would allow the adding of wrappers to lines like you suggested so I wouldn't have to ask list maintainers to the same.

**Comment by stamparm** [comment]
this list is a generic (free and open for all), not targeting a specific product (e.g. adblock). thus, not planning to expand it
