### ISSUE TITLE
False positive - slug.vercel.app

### ISSUE THREAD

**Issue by zhg7** [stamparm/aux#13]
@stamparm @MikhailKasimov

Listed in [maltrail-malware-domains.txt](https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt)

It seems to be a legit URL shortener: https://github.com/pheralb/slug

**Comment by MikhailKasimov** [comment]
Hello!

You're correct.

Fixed: https://github.com/stamparm/maltrail/commit/7460f550e6b21ad6797e49d855aacc2e6646eee3 and whitelisted: https://github.com/stamparm/maltrail/commit/cde337dc0ea51f1abaaa39b88d2f6a4124b7c5d3

Thank you for the alert and sorry for FP!
