### ISSUE TITLE
msauth.net

### ISSUE THREAD

**Issue by Foosec** [stamparm/aux#2]
It seems a legitimate microsoft domain got it to the maltrail-malware-domains list; **msauth.net**.
Its listed https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide
there as a legitimate microsoft endpoint for Office 365.

**Comment by PeterDaveHello** [comment]
Looks like it's cleaned up already in https://github.com/stamparm/maltrail/commit/22a4f48f3eca19583b8a94efef63780fbd182f65 on Sun Aug 8 16:02:14 2021 +0200

**Comment by stamparm** [comment]
sorry, didn't even see this issue :P. yea, it should be cleaned
