### ISSUE TITLE
t2m.io is not a malware domain.

### ISSUE THREAD

**Issue by crocket** [stamparm/aux#4]
maltrail-malware-domains.txt contains t2m.io which is a URL shortener.

Some malware domains use t2m.io to get short URLs. But, it also has legitimate users.

**Comment by MikhailKasimov** [comment]
Fix: https://github.com/stamparm/maltrail/commit/bb76a36e705e62d7cd2f7e658fab575b1178fbb2

**Comment by stamparm** [comment]
Hi @crocket.

Sorry, haven't got a notification mail. Update will be propagated with the next automatic update (in couple of hours)

Best regards
