### ISSUE TITLE
False Positives for wire.com

### ISSUE THREAD

**Issue by comawill** [stamparm/aux#5]
The `maltrail-malware-domains.txt` list blocks several domains from *.wire.com which breaks Wire.

* `account.wire.com`
* `teams.wire.com`
* `prod-nginz-https.wire.com`
* `clientblacklist.wire.com`
* `prod-nginz-ssl.wire.com`

**Comment by comawill** [comment]
Also the following domains are part of Wire's test infrastructure and not malicious

* `account.qa-demo.wire.link`
* `assets.qa-demo.wire.link`
* `nginz-https.qa-demo.wire.link`
* `nginz-ssl.qa-demo.wire.link`
* `teams.qa-demo.wire.link`
* `webapp.qa-demo.wire.link`
* `staging-nginz-https.zinfra.io`
* `taging-nginz-ssl.zinfra.io`
* `wire-account-staging.zinfra.io`
* `wire-teams-staging.zinfra.io'

**Comment by stamparm** [comment]
Hi @comawill.

This will be propagated with the next automatic update (in couple of hours)

Best regards
