### ISSUE TITLE
False positive: Shaparak (bpm.shaparak.ir), the official domain of Iran's national online banking portal.

### ISSUE THREAD

**Issue by FaridZelli** [stamparm/aux#6]
Noticed that Shaparak was getting blocked by [Energized Protection](https://energized.pro/) (via [this list](https://github.com/notracking/hosts-blocklists)), and so I eventually traced it back to here. Interestingly non of the malicious domains made it into the list, which leads me to believe it may be from another blocklist entirely. Either way, it's a false positive and should be whitelisted.

To be clear, that is https://shaparak.ir/

Thanks for your work!

**Comment by MikhailKasimov** [comment]
Hello!

- FP is fixed via: https://github.com/stamparm/maltrail/commit/4f8aa8c6592a11ad64b3b038bf51502ebb8db556
- ```shaparak.ir``` and ```bpm.shaparak.ir``` domains are whitelisted via: https://github.com/stamparm/maltrail/commit/f245e4cb77f0a7ec8b7ecf33f2b69bd063b0c1ca

Thank you for FP reporting and sorry for inconvenience!
