### ISSUE TITLE
False Positives for autism-101.com

### ISSUE THREAD

**Issue by autism-101** [stamparm/aux#7]
The maltrail-malware-domains.txt list blocks my static html https://autism-101.com website hosted on Cloudflare.

**Comment by MikhailKasimov** [comment]
Fixed in https://github.com/stamparm/maltrail/commit/1aa132c1534beedb357c31bd14f9b9f04cf74860 . Sorry for inconvenience with FP.

**Comment by autism-101** [comment]
Thank you!
