### ISSUE TITLE
Invalid domains on list:

### ISSUE THREAD

**Issue by pallebone** [stamparm/aux#8]
Hi there,

Thank you for this list. Pihole reports some daomains are invalid, eg:
  [i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 290973 exact domains and 0 ABP-style domains (ignored 13 non-domain entries)
      Sample of non-domain entries:
        - "gettask"
        - "reportupdates"
        - "fbc8213450838f7ae251d4"
        - "gettasks"
        - "online-etk"

Kind regards
Peter

**Comment by MikhailKasimov** [comment]
Hello!

Done:

[1] https://github.com/stamparm/maltrail/commit/b437b3887de5e6d6cd331771f01b06c5c1d456f8
[2] https://github.com/stamparm/maltrail/commit/b5b6bbe3fc2bc29720e975adbac841ae9675c426
[3] https://github.com/stamparm/maltrail/commit/380de22f4159fa4fa721962b04a731c557f4a519
[4] https://github.com/stamparm/maltrail/commit/fd833aabb2f1698ad58e4ffd73b4cca90840da8c

Thanks for report of junk/orphan records!

**Comment by pallebone** [comment]
Does it take time to update?
I tried again but still got this. Could be a delay?

Pete

  [i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 290973 exact domains and 0 ABP-style domains (ignored 13 non-domain entries)
      Sample of non-domain entries:
        - "gettask"
        - "reportupdates"
        - "fbc8213450838f7ae251d4"
        - "gettasks"
        - "online-etk"

**Comment by MikhailKasimov** [comment]
> Does it take time to update? I tried again but still got this. Could be a delay?

Yes, it takes some time, during 24 hours (as far as I remember), ```/maltrail-malware-domains.txt``` will get listed updates .

> Pete
> 
> [i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt [✓] Status: Retrieval successful [✓] Parsed 290973 exact domains and 0 ABP-style domains (ignored 13 non-domain entries) Sample of non-domain entries: - "gettask" - "reportupdates" - "fbc8213450838f7ae251d4" - "gettasks" - "online-etk"

**Comment by pallebone** [comment]
Ok will try tomorrow :)

**Comment by MikhailKasimov** [comment]
@pallebone Hello!

As I can see, mentioned junk/orphan records are gone away. Initially it was "ignored 13 non-domain entries" <-- could you, please, provide other non-domain entries? Thank you!

**Comment by pallebone** [comment]
Yes here are 5 more:

  [i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 291076 exact domains and 0 ABP-style domains (ignored 5 non-domain entries)
      Sample of non-domain entries:
        - "rbacrbyq2czpwn15net"
        - "mobile-activity-site"
        - "9904.a"
        - "reken-bhf.d"
        - "p1cldcheq"

**Comment by MikhailKasimov** [comment]
Fixed in:

[1] https://github.com/stamparm/maltrail/commit/6e41ca4a9e96384e6e6df3179fa1377a7953a152
[2] https://github.com/stamparm/maltrail/commit/92c524ec5da509ecfbce30d87bbb8774e099fc48
[3] https://github.com/stamparm/maltrail/commit/233c4460bdd6eb1996ec3f43a4b6fc06c13e9e72
[4] https://github.com/stamparm/maltrail/commit/daa81ccef7cab212efdce9e9c09b51fefdf91fed
[5] https://github.com/stamparm/maltrail/commit/9005488078e846173e047143a2859f58ee859eb2

Thank you for hint!

**Comment by MikhailKasimov** [comment]
@pallebone Hello! Please, re-check the non-domain entries counter now. If = 0, bug-report can be closed. Thank you!

**Comment by pallebone** [comment]
[i] Target: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 291146 exact domains and 0 ABP-style domains (ignored 0 non-domain entries)
  [i] List has been updated

**Comment by pallebone** [comment]
Thanks :)
