### ISSUE TITLE
FP: redalert.nshc.net

### ISSUE THREAD

**Issue by hagezi** [stamparm/aux#9]
@stamparm @MikhailKasimov false positive:

List: https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt
Blocked domain: `redalert.nshc.net`

Red Alert is the offensive research department that is part of NSHC group. Red Alert department has 10 years of reputable history, starting from Korea, with invaluable customer feedback throughout the world. Red Alert strives to be Asia’s No.1 Offensive Security Research Company, expanding its operations globally. Currently Red Alert operates in 4 countries under NSHC: Singapore, Korea, Japan and Indonesia, serving clients and partners in over 15 countries worldwide.

**Comment by MikhailKasimov** [comment]
Hello!

Fix: https://github.com/stamparm/maltrail/commit/4843694ed00cafcd3d01b6f3d77f955b594a6857
Whitelist: https://github.com/stamparm/maltrail/commit/7ef2c56a64dd1f9e0d6fdf5f9c05879d83aae43d

Initially:
![image](https://github.com/stamparm/aux/assets/7167300/6bd2d9ac-7eaa-4595-8837-796f96017d97)

Anyway, sorry for FP.
